### Health check
GET http://localhost:8000/health

### Ping
GET http://localhost:8000/api/ping


### Conversation #######################################################################

### Create new conversation
POST http://localhost:8000/api/conversations
Content-Type: application/json

{
  "metadata": {"topic": "demo"}
}

### Create new conversation with items
POST http://localhost:8000/api/conversations
Content-Type: application/json

{
  "metadata": {"topic": "demo"},
  "messages": [
      {
        "role": "user",
        "content": "How many vacation days do I get?"
      }
    ],
  "context": {
    "timezone_offset_min":420,
    "timezone":"America/Phoenix",
    "locale": "en-US"
  },
  "client": {
    "channel": "webchat",
    "deviceId": "optional-browser-id",
    "userId": "user-j8bmcV3K3w2pFojdbRcPM3O8"
  }
}

### Get a Conversation
GET http://localhost:8000/api/conversations/conv_123
Content-Type: application/json


### Get a Conversation messages
GET http://localhost:8000/api/conversations/conv_123/messages
Content-Type: application/json

### Get a Conversation message
GET http://localhost:8000/api/conversations/conv_123/messages/345
Content-Type: application/json

### Post new conversation message
POST http://localhost:8000/api/conversations/conv_123/messages
Content-Type: application/json

{
  "metadata": {"topic": "demo"},
  "messages": [
      {
        "role": "user",
        "content": "Come one, let's do this!!!"
      }
    ],
  "context": {
    "timezone_offset_min":420,
    "timezone":"America/Phoenix",
    "locale": "en-US"
  },
  "client": {
    "channel": "webchat",
    "deviceId": "optional-browser-id",
    "userId": "user-j8bmcV3K3w2pFojdbRcPM3O8"
  }
}


### OpenAPI
GET http://localhost:8000/docs

