"""Pydantic models for conversations."""

from typing import Any

from pydantic import BaseModel, Field

# class ChunkResult(BaseModel):
#     content: str
#     source: str
#     score: float


# class MessageResponse(BaseModel):
#     status: str
#     trace_id: str
#     duration_ms: float
#     text: str
#     embedding_dimensions: int
#     embedding_preview: list[float]
#     chunks: list[ChunkResult]
#     messages: list[dict]


class MessageCreate(BaseModel):
    """Model for creating a new message, without an ID or create_time (which will be generated by the system)."""

    type: str = "message"
    role: str
    content: str


class Message(BaseModel):
    """Model representing a message in a conversation, including a unique ID and creation timestamp."""

    id: str | None = Field(..., description="The unique ID of the message")
    type: str = "message"
    role: str
    content: str
    create_time: int = Field(
        ...,
        description="The time at which the message was created, measured in seconds since the Unix epoch.",
    )


class ConversationItemListCreate(BaseModel):
    """Model for creating new messages in a conversation, which includes a list of MessageCreate objects."""

    messages: list[MessageCreate]


class ConversationItemList(BaseModel):
    """Model representing a list of messages in a conversation, along with pagination information such as first_id, last_id, and has_more."""

    object: str = "list"
    data: list[Message]
    first_id: str
    last_id: str
    has_more: bool


class ConversationCreate(BaseModel):
    """Model for creating a new conversation, which includes optional metadata and an initial list of messages (as MessageCreate objects). The context and client fields are included for potential future use but are currently set to None by default."""

    metadata: dict[str, Any] = ({},)
    messages: list[MessageCreate] = []
    context: dict | None = None
    client: dict | None = None


class Conversation(BaseModel):
    """Model representing a conversation, which includes a unique ID, creation timestamp, metadata, and a list of messages (as Message objects). The object field is set to "conversation" to indicate the type of the model."""

    id: str
    object: str = "conversation"
    create_time: int = Field(
        ...,
        description="The time at which the message was created, measured in seconds since the Unix epoch.",
    )
    metadata: dict[str, Any] = ({},)
    messages: list[Message]
